server:
  port: 8002


spring:
  application:
    name: items-service


config:
  baseurl:
    endpoint:
      products-service: http://products-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/